- name: install APT Transport HTTPS
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: true

- name: create directory for APT keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644
    owner: root
    group: root
    force: true
  become: true

- name: get architecture
  shell: dpkg --print-architecture
  register: architecture

- name: get debian release version
  shell: lsb_release -cs
  register: debian_version

- name: add docker APT repository for Debian
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ debian_version.stdout }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: true

- name: install container runtime
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  become: true

- name: add containerd default config
  shell: containerd config default | tee /etc/containerd/config.toml
  become: true

- name: make containerd use SystemdCgroup
  shell: sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

- name: change the image driver of containerd
  shell: sudo sed -i 's/sandbox_image = "registry.k8s.io\/pause:3.8"/sandbox_image = "registry.k8s.io\/pause:3.10"/g' /etc/containerd/config.toml

- name: restart containerd
  shell: systemctl restart containerd
  become: true
