- name: check if kubernetes cluster is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_cluster_initialized

- name: init cluster
  shell: |
    kubeadm init \
      --control-plane-endpoint={{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443 \
      --apiserver-advertise-address={{ hostvars[groups['masters'][0]]['ansible_host'] }} \
      --upload-certs \
      --pod-network-cidr={{ kubernetes.pod_network_cidr }} \
      --v 5 \
      >> {{  kubernetes.logs_cluster  }}
  args:
    chdir: /var/log
  when: not k8s_cluster_initialized.stat.exists
  become: true

- name: create kube config directory
  file:
    path: "{{ kubernetes.config }}"
    state: directory
    mode: 0755

- name: print join command
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command
  become: true

- name: set join command fact
  set_fact:
    join_worker_node_command: "{{ kubernetes_join_command['stdout'] | trim }}"

- name: display join command
  debug:
    msg: "Join command is {{ join_worker_node_command }}"

- name: copy admin.conf to user's kube config
  copy:
    src: "{{ kubernetes.kube_config_admin }}"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true
    mode: 0644
  become: true

- name: copy kubeconfig to ansible host
  fetch:
    src: "~/.kube/config"
    dest: "{{ playbook_dir }}/config"
    flat: yes

- name: download Calico manifest
  get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ cni.calico.version }}/manifests/calico.yaml"
    dest: "/tmp/calico.yaml"
    mode: 0644

- name: apply Calico manifest
  shell: kubectl apply -f /tmp/calico.yaml
