- name: Install k3s server with specific version and disable traefik
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s.version }} INSTALL_K3S_EXEC={{ k3s.exec }} sh -

- name: Get node token for agent nodes
  become: true
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token_result

- name: Set node token fact
  set_fact:
    node_token: "{{ node_token_result['content'] | b64decode | trim }}"

- name: Display node token
  debug:
    msg: "Node token is {{ node_token }}"

- name: Copy k3s kubeconfig to ansible host
  become: yes
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ playbook_dir }}/k3s.yaml"
    flat: yes
