- name: update packages
  apt:
    update_cache: yes
  become: true

- name: disable swap
  shell: swapoff -a
  become: true

- name: remove swap entry from /etc/fstab
  lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent
  become: true

- name: enable IPv4 packet forwarding
  shell: |
    cat <<EOF | tee /etc/sysctl.d/k8s.conf
    net.ipv4.ip_forward = 1
    EOF
  become: true

- name: apply sysctl params without reboot
  shell: sysctl --system
  become: true
